name: Verification

on:  
  push:
    branches:
      - vcalyx
      - priyasrikumar-patch-1

# Ensures that only the latest commit of a PR can execute the actions.
# Useful for cancelling job when a sequence of commits are quickly added.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build VCalyx
    runs-on: ubuntu-latest
    container: ghcr.io/cucapra/calyx:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get bwrap
      run: |
        apt-get update -y
        apt-get install -y bubblewrap
    - name: Use OCaml 4.13.1
      uses: ocaml/setup-ocaml@v2
      with:
          ocaml-compiler: 4.13.1
    - name: Checkout commit that triggered run
      working-directory: home/calyx
      run: |
        git fetch --all
        git checkout $GITHUB_SHA
    - name: Install dependencies
      working-directory: home/calyx
      run: |
        opam install . --deps-only 
    - name: Build with dune
      working-directory: home/calyx
      run: |
        opam exec -- dune build
